// <auto-generated />

using System;
using System.Linq;
using WebApplication1.Web.Enums;
using WebApplication1.Web.Models;

namespace WebApplication1.Web.DatabaseContext
{
    /// <summary>
    /// Application Database Extension for seeding sample data
    /// </summary>
    public static class AppDbContextExtensions
    {
        /// <summary>
        /// Seeds sample data
        /// </summary>
        /// <param name="context"></param>
        public static void EnsureSeedData(this AppDbContext context)
        {
            if (context.Clients.Any() || context.Categories.Any())
            {
                return;
            }

            var partnersCategory = context.Categories.Add(new Category { Name = "Partners" }).Entity;
            var japaneseItCategory = context.Categories.Add(new Category { Name = "日本IT企業" }).Entity;
            var otherCategory = context.Categories.Add(new Category { Name = "Other" }).Entity;

            context.Clients.AddRange(
                new Client
                {
                    Name = "Sample1",
                    Email = "Sample1@contoso.com",
                    Fax = "111111",
                    Phone = "222222",
                    Status = ClientStatus.Active,
                    Address = "1 Street, Sample Road, SA1 4AA, IN",
                    CreatedOn = DateTime.Now,
                    Category = partnersCategory
                },
                new Client
                {
                    Name = "Sample2",
                    Email = "Sample2@contoso.com",
                    Fax = "222222",
                    Phone = "333333",
                    Status = ClientStatus.Inactive,
                    Address = "1 Street, Sample Road, SA1 4AA, IN",
                    CreatedOn = DateTime.Now,
                    Category = japaneseItCategory
                },
                new Client
                {
                    Name = "Sample3",
                    Email = "Sample3@contoso.me",
                    Fax = "333333",
                    Phone = "444444",
                    Status = ClientStatus.Archived,
                    Address = "1 Street, Sample Road, SA1 4AA, IN",
                    CreatedOn = DateTime.Now,
                    Category = otherCategory
                },
                new Client
                {
                    Name = "Sample4",
                    Email = "Sample4@contoso.com",
                    Fax = "444444",
                    Phone = "555555",
                    Status = ClientStatus.Pending,
                    Address = "1 Street, Sample Road, SA1 4AA, IN",
                    CreatedOn = DateTime.Now,
                    Category = partnersCategory
                },
                new Client
                {
                    Name = "Sample5",
                    Email = "Sample5@contoso.com",
                    Fax = "555555",
                    Phone = "666666",
                    Status = ClientStatus.Active,
                    Address = "1 Street, Sample Road, SA1 4AA, IN",
                    CreatedOn = DateTime.Now,
                    Category = japaneseItCategory
                }
            );

            context.SaveChanges();
        }
    }
}
